vertx-service-discovery-bridge-kubernetes/src/main/java/io/vertx/servicediscovery/hazelcast/HazelcastKubernetesDiscoveryStrategy.java

see https://github.com/vert-x3/vertx-service-discovery/issues/28

Possible NullPointer when logging InetAddress in HazelcastKubernetesDiscoveryStrategy and clean up

---

vertx-service-discovery-backend-redis/src/main/asciidoc/groovy/index.adoc
vertx-service-discovery-backend-redis/src/main/asciidoc/java/index.adoc
vertx-service-discovery-backend-redis/src/main/asciidoc/js/index.adoc
vertx-service-discovery-backend-redis/src/main/asciidoc/ruby/index.adoc
vertx-service-discovery-bridge-consul/src/main/asciidoc/groovy/index.adoc
vertx-service-discovery-bridge-consul/src/main/asciidoc/java/index.adoc
vertx-service-discovery-bridge-consul/src/main/asciidoc/js/index.adoc
vertx-service-discovery-bridge-consul/src/main/asciidoc/ruby/index.adoc
vertx-service-discovery-bridge-docker-links/src/main/asciidoc/groovy/index.adoc
vertx-service-discovery-bridge-docker-links/src/main/asciidoc/java/index.adoc
vertx-service-discovery-bridge-docker-links/src/main/asciidoc/js/index.adoc
vertx-service-discovery-bridge-docker-links/src/main/asciidoc/ruby/index.adoc
vertx-service-discovery-bridge-kubernetes/src/main/asciidoc/groovy/index.adoc
vertx-service-discovery-bridge-kubernetes/src/main/asciidoc/java/index.adoc
vertx-service-discovery-bridge-kubernetes/src/main/asciidoc/js/index.adoc
vertx-service-discovery-bridge-kubernetes/src/main/asciidoc/ruby/index.adoc
vertx-service-discovery/.vertx/debug-js/vertx-js/async_map.js
vertx-service-discovery/.vertx/debug-js/vertx-js/counter.js
vertx-service-discovery/.vertx/debug-js/vertx-js/future.js
vertx-service-discovery/.vertx/debug-js/vertx-js/http_connection.js
vertx-service-discovery/.vertx/debug-js/vertx-js/timeout_stream.js
vertx-service-discovery/.vertx/debug-js/vertx-js/util/utils.js
vertx-service-discovery/.vertx/debug-js/vertx-js/vertx.js
vertx-service-discovery/src/main/asciidoc/groovy/index.adoc
vertx-service-discovery/src/main/asciidoc/java/index.adoc
vertx-service-discovery/src/main/asciidoc/js/index.adoc
vertx-service-discovery/src/main/asciidoc/ruby/index.adoc
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/Record.java
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/RecordTest.java

Lots of generated files, but it basically boils down to having overridden the `equals()` and `hashCode()` members of the `Record` data object.

Record reference equality

---

vertx-service-discovery/pom.xml
vertx-service-discovery/src/main/asciidoc/groovy/index.adoc
vertx-service-discovery/src/main/asciidoc/java/index.adoc
vertx-service-discovery/src/main/asciidoc/js/index.adoc
vertx-service-discovery/src/main/asciidoc/ruby/index.adoc
vertx-service-discovery/src/main/generated/io/vertx/rxjava/servicediscovery/types/RedisDataSource.java
vertx-service-discovery/src/main/groovy/io/vertx/groovy/servicediscovery/types/RedisDataSource.groovy
vertx-service-discovery/src/main/java/examples/RedisDataSourceExamples.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/package-info.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/RedisDataSource.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/impl/RedisDataSourceImpl.java
vertx-service-discovery/src/main/resources/META-INF/services/io.vertx.servicediscovery.spi.ServiceType
vertx-service-discovery/src/main/resources/vertx-service-discovery-js/redis_data_source.js
vertx-service-discovery/src/main/resources/vertx-service-discovery/redis_data_source.rb
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/types/RedisDataSourceTest.java

Add Redis data source service type implementation as well as document.

Redis data source implementation

---

vertx-service-discovery/pom.xml
vertx-service-discovery/src/main/java/examples/MongoDataSourceExamples.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/MongoDataSource.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/impl/MongoDataSourceImpl.java
vertx-service-discovery/src/main/resources/META-INF/services/io.vertx.servicediscovery.spi.ServiceType
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/types/MongoDataSourceTest.java

Just a missing implementation... Test passed, code style checked, Eclipse license signed.

Simply add a Mongo DataSource, based on other implementations

---

vertx-service-discovery-bridge-kubernetes/src/main/asciidoc/js/index.adoc
vertx-service-discovery-bridge-kubernetes/src/main/asciidoc/ruby/index.adoc
vertx-service-discovery/pom.xml
vertx-service-discovery/src/main/asciidoc/groovy/index.adoc
vertx-service-discovery/src/main/asciidoc/java/index.adoc
vertx-service-discovery/src/main/asciidoc/js/index.adoc
vertx-service-discovery/src/main/asciidoc/ruby/index.adoc
vertx-service-discovery/src/main/java/examples/HTTPEndpointExamples.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/ServiceDiscovery.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/package-info.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/HttpEndpoint.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/impl/HttpEndpointImpl.java
vertx-service-discovery/src/main/resources/vertx-service-discovery-js/http_endpoint.js
vertx-service-discovery/src/main/resources/vertx-service-discovery/http_endpoint.rb
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/polyglot/MyRXVerticle.java
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/polyglot/MyVerticle.java
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/polyglot/PolyglotUsageTest.java
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/types/HttpEndpointTest.java
vertx-service-discovery/src/test/resources/polyglot/my-verticle.js

This PR allows retrieving a WebClient from an HTTP endpoint.
It fixes #52.

Add web client support

---

vertx-service-discovery/src/test/java/io/vertx/servicediscovery/types/HttpEndpointTest.java

Use local https server to avoid issues with remote services
Use webClient instead of HttpClient:
- easier to program
- better error reports
- easy integration with testContext

Fixes #59 io.vertx.servicediscovery.types.HttpEndpointTest.testRecordCreation

---

pom.xml
vertx-service-discovery-backend-consul/pom.xml
vertx-service-discovery-backend-consul/src/main/java/examples/Examples.java
vertx-service-discovery-backend-consul/src/main/java/examples/package-info.java
vertx-service-discovery-backend-consul/src/main/java/io/vertx/servicediscovery/backend/consul/ConsulBackendService.java
vertx-service-discovery-backend-consul/src/main/java/io/vertx/servicediscovery/backend/consul/package-info.java
vertx-service-discovery-backend-consul/src/main/resources/META-INF/services/io.vertx.servicediscovery.spi.ServiceDiscoveryBackend
vertx-service-discovery-backend-consul/src/test/java/io/vertx/servicediscovery/backend/consul/ConsulBackendTest.java

Create a Consul-backend. See vert-x3/vertx-service-discovery#53 .

Consul backend

---

vertx-service-discovery/src/main/java/io/vertx/servicediscovery/package-info.java

Fixed a typo in the doc

---

vertx-service-discovery-bridge-kubernetes/src/main/resources/META-INF/services/com.hazelcast.spi.discovery.DiscoveryStrategyFactory

…that shouldn't have been in here

Removed reference to the old HazelcastDiscoverStrategy

---

vertx-service-discovery-bridge-consul/pom.xml
vertx-service-discovery-bridge-consul/src/main/java/io/vertx/servicediscovery/consul/ConsulServiceImporter.java
vertx-service-discovery-bridge-consul/src/main/java/io/vertx/servicediscovery/consul/package-info.java
vertx-service-discovery-bridge-consul/src/test/java/io/vertx/servicediscovery/consul/ConsulServiceImporterTest.java

rewrite bridge-consul with vertx-consul-client

---

vertx-service-discovery-bridge-consul/src/main/java/io/vertx/servicediscovery/consul/ConsulServiceImporter.java

avoid a ConcurrentModificationException

fix bug with de-registering services 

---

vertx-service-discovery-bridge-consul/src/main/java/io/vertx/servicediscovery/consul/ConsulServiceImporter.java
vertx-service-discovery-bridge-consul/src/test/java/io/vertx/servicediscovery/consul/ConsulServiceImporterTest.java

Implements fix for #83 
Modify to use the /health endpoint in consul to ensure we are only importing healthy services.
Previous code was setting the imported service path to the service address. Consul does not have the concept of a service path, so this was removed and test modified to ensure this does not get set
Also includes a refactoring of tests to generate mocked consul response JSON consisently

Import healthy

---

vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/EventBusService.java
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/types/ServiceProxiesTest.java

Enable configuration for EventBusService

---

pom.xml
vertx-service-discovery-backend-consul/src/main/resources/META-INF/MANIFEST.MF
vertx-service-discovery-backend-redis/src/main/resources/META-INF/MANIFEST.MF
vertx-service-discovery-backend-zookeeper/src/main/resources/META-INF/MANIFEST.MF
vertx-service-discovery-bridge-consul/src/main/resources/META-INF/MANIFEST.MF
vertx-service-discovery-bridge-docker-links/src/main/resources/META-INF/MANIFEST.MF
vertx-service-discovery-bridge-docker/src/main/resources/META-INF/MANIFEST.MF
vertx-service-discovery-bridge-kubernetes/src/main/resources/META-INF/MANIFEST.MF
vertx-service-discovery-bridge-zookeeper/src/main/resources/META-INF/MANIFEST.MF
vertx-service-discovery/src/main/resources/META-INF/MANIFEST.MF

Signed-off-by: afloarea <adrianfloarea07@yahoo.com>
Motivation:
Add automatic module name as per vert-x3/issues#524

Add automatic module names

---

vertx-service-discovery-bridge-zookeeper/src/main/java/io/vertx/servicediscovery/zookeeper/ZookeeperServiceImporter.java

Fix unregisterAllServices()

---

vertx-service-discovery-bridge-kubernetes/src/test/java/io/vertx/servicediscovery/kubernetes/KubernetesServerTest.java
vertx-service-discovery/src/main/asciidoc/dataobjects.adoc
vertx-service-discovery/src/main/generated/io/vertx/servicediscovery/ServiceDiscoveryOptionsConverter.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/ServiceDiscoveryOptions.java

Removed the autoRegistrationOfImporters attribute from ServiceDiscoveryOptions

---

vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/MessageSource.java
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/types/MessageSourceTest.java

Preserve metadata when creating MessageSource record with type info

---

vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/HttpEndpoint.java
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/types/HttpEndpointTest.java

Motivation:
This PR fixing the issue #141

Fix get web client func

---

vertx-service-discovery-bridge-kubernetes/src/main/java/io/vertx/servicediscovery/kubernetes/KubernetesServiceImporter.java
vertx-service-discovery-bridge-kubernetes/src/test/java/io/vertx/servicediscovery/kubernetes/KubernetesServerTest.java

Fixes #146
Avoids redundant service (un-)publications.

KubernetesServiceImporter: process watch events in batches

---

vertx-service-discovery-bridge-consul/src/main/java/io/vertx/servicediscovery/consul/ConsulServiceImporter.java
vertx-service-discovery-bridge-consul/src/test/java/io/vertx/servicediscovery/consul/ConsulServiceImporterTest.java

Fallback to Node.Address if Service.Address is empty when building Consul record

---

vertx-service-discovery-bridge-docker/pom.xml
vertx-service-discovery-bridge-docker/src/main/java/io/vertx/servicediscovery/docker/DockerServiceImporter.java
vertx-service-discovery-bridge-docker/src/test/java/io/vertx/servicediscovery/docker/DockerBridgeTest.java

Signed-off-by: Paulo Lopes <pmlopes@gmail.com>
Motivation:
https://github.com/vert-x3/issues/issues/593

Avoid depending on jaxrs

---

vertx-service-discovery-backend-zookeeper/pom.xml
vertx-service-discovery-bridge-docker/pom.xml
vertx-service-discovery-bridge-zookeeper/pom.xml

Signed-off-by: Paulo Lopes <pmlopes@gmail.com>

Update guava to use a CVE free version

---

vertx-service-discovery/src/main/java/io/vertx/servicediscovery/ServiceDiscovery.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/impl/DiscoveryImpl.java
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/impl/DiscoveryImplTestBase.java

Motivation:
Facilitate the reading of usage events when consume the usage address.

Add constants for usage events

---

vertx-service-discovery-backend-consul/src/main/java/io/vertx/servicediscovery/backend/consul/package-info.java
vertx-service-discovery-backend-redis/src/main/java/io/vertx/servicediscovery/backend/redis/package-info.java
vertx-service-discovery-backend-zookeeper/src/main/java/io/vertx/servicediscovery/backend/zookeeper/package-info.java
vertx-service-discovery-bridge-consul/src/main/java/io/vertx/servicediscovery/consul/package-info.java
vertx-service-discovery-bridge-docker-links/src/main/java/io/vertx/servicediscovery/docker/package-info.java
vertx-service-discovery-bridge-docker/src/main/java/io/vertx/servicediscovery/docker/package-info.java
vertx-service-discovery-bridge-kubernetes/src/main/java/io/vertx/servicediscovery/kubernetes/package-info.java
vertx-service-discovery-bridge-zookeeper/src/main/java/io/vertx/servicediscovery/zookeeper/package-info.java
vertx-service-discovery/pom.xml
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/ServiceDiscovery.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/package-info.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/spi/ServicePublisher.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/HttpEndpoint.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/JDBCDataSource.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/MessageSource.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/MongoDataSource.java
vertx-service-discovery/src/main/java/io/vertx/servicediscovery/types/RedisDataSource.java
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/polyglot/PolyglotUsageTest.java
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/types/MongoDataSourceTest.java
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/types/RedisDataSourceTest.java

See vert-x3/issues#612
Also, replaced embedded Mongo/Redis with testcontainers

Deprecate callbacks

---

vertx-service-discovery-bridge-zookeeper/pom.xml
vertx-service-discovery-bridge-zookeeper/src/main/java/io/vertx/servicediscovery/zookeeper/JsonObjectSerializer.java

Avoid databind

---

vertx-service-discovery/src/main/java/io/vertx/servicediscovery/impl/DiscoveryImpl.java
vertx-service-discovery/src/test/java/io/vertx/servicediscovery/impl/SlowDiscoveryBackendTest.java
vertx-service-discovery/src/test/resources/META-INF/services/io.vertx.servicediscovery.spi.ServiceDiscoveryBackend

Fix premature update announcement
